### ISSUE TITLE
Benchmark plot

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/BioIO#32]
I think we should have a benchmark plot where we compare performance of BioIO, seqtk, Heng Li, and Python. What should we plot?
- [ ] total time for parsing file with long reads
- [ ] total time for parsing file with short reads
- [ ] reads parsed per second of the above
- [x] bases parsed per second of the above

**Comment by RasmusFonseca** [comment]
Probably there should be benchmarking with some kind of trivial processing of this data. Counting number of nucleotides or number of A's or something.

**Comment by maasha** [comment]
bases per second then?
