### ISSUE TITLE
Benchmark against seqtk

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/BioIO#5]
To my knowledge seqtk is has the fastest parsers, but the code is ugly! We should benchmark against it!

https://github.com/lh3/seqtk

Let's setup a benchmark dir and a Makefile for running benchmarks.

**Comment by RasmusFonseca** [comment]
Benchmark folder up. We need some fastas in there. Any good suggestions? Should be both protein (many entries), rna (many entries) and dna files (big entries).

**Comment by AndreasDahl** [comment]
If we want to have big files in the repo, we should strongly consider using [git LFS](https://git-lfs.github.com/)

**Comment by maasha** [comment]
fixed
